hash-format = "sha256"

[[files]]
file = ".editorconfig"
hash = "82782271d3e3a34d29ddaa4dcbad17c5f516fafddbc58202c47333f8658a5602"

[[files]]
file = "config/create-common.toml"
hash = "c0e90fd1c6d4a0498cdbd259936812e35b1461eb0d11b4967e2ba32032a5bd44"

[[files]]
file = "config/customsplashscreen.json5"
hash = "0c4ebb39d1bcd398d6c2c7b42c9f2ac641741294e0efe96c6f30a86a7934b8fa"

[[files]]
file = "config/customsplashscreen/background.png"
hash = "67d20ac3afe9538286de7c2a44f6bea546bdccf116b5246d0f5d6ce2d9a8b0a0"

[[files]]
file = "config/customsplashscreen/mojangstudios.png"
hash = "27b2ea2946ca5b00841ce7d1813b42dfb7e36b12ad50c7c9bea09053ac226cf3"

[[files]]
file = "config/customsplashscreen/mojank.png"
hash = "bb2080abef56e6ec5ab6bd4576e9e3dc7e15817410e02051553475f4cd3fcd8d"

[[files]]
file = "config/customsplashscreen/progressbar.png"
hash = "e2e0555e30fd677e05570551f36d3a95fd844dcadc62b15e4f901c3442a5e3c7"

[[files]]
file = "config/customsplashscreen/progressbar_background.png"
hash = "6e2fa0adee9638b3e8f36e75ad048f0abb0de2d06b591961c6b2aff943fd46f2"

[[files]]
file = "config/entityculling.json"
hash = "a7395d0ba0d91fad7d584e159dc5428a22554cbb9f4f2c5c5262edfe74362418"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"
hash = "684a97145572aba3c5dc320716c6cb66ff36180ae8f149b9d60249414c83d309"

[[files]]
file = "config/ftbquests/quests/chapters/advancements.snbt"
hash = "5580728781a920621990b3fcf16c5f77e8b0337245a5b17f82951c519e109f98"

[[files]]
file = "config/ftbquests/quests/chapters/market.snbt"
hash = "8dd239ca07a9c7420537e3d8b8a357b8848e94fa508527e2d585cc083c43af86"

[[files]]
file = "config/ftbquests/quests/chapters/metallurgy.snbt"
hash = "cb7ef2285b9620830a0abfa0fa6323f3a2e48f648fdadd696e0ae1f6cc958e97"

[[files]]
file = "config/ftbquests/quests/chapters/overview.snbt"
hash = "1573137f6fc2afef9fca929fbbfc6179f03794cae9eb5a6d49c929ff46384429"

[[files]]
file = "config/ftbquests/quests/chapters/professions.snbt"
hash = "40fa98d2f0eeed923e2d69b635ab9f2e14c1800bda2b2068666028136200c86a"

[[files]]
file = "config/ftbquests/quests/chapters/shipments.snbt"
hash = "45938d489291b856e313ccc5c8d8a2625c45360912b7a74164fe610ab90fe453"

[[files]]
file = "config/ftbquests/quests/chapters/stage_1.snbt"
hash = "9d1e5ee45758c86847a0963618ccd1cfd5e25fae4bc0b2cef6ea1193fcaedf29"

[[files]]
file = "config/ftbquests/quests/chapters/stage_2.snbt"
hash = "8d310817be4dde6f0b17d63adb2ee0caffc35b292796084cc68197a87ef7672a"

[[files]]
file = "config/ftbquests/quests/chapters/stage_3.snbt"
hash = "bb10b49a7ffeac102adeaa29e4ff08dde473554d305a686053344eece028d912"

[[files]]
file = "config/ftbquests/quests/chapters/stage_4.snbt"
hash = "e633f08a5ab08591cbf56a2270e2a3dbc5abeeeab631d08cf045d4ba03623181"

[[files]]
file = "config/ftbquests/quests/chapters/stage_4a.snbt"
hash = "a6048ee9920224aa02cb70313fd5f5595bd4281d85a0e9205449b7eb3eef089f"

[[files]]
file = "config/ftbquests/quests/chapters/stage_5.snbt"
hash = "1def5fd8dbe74d51209fbdac83402b6808e66293e9b6d69d6c08ef0760646dea"

[[files]]
file = "config/ftbquests/quests/chapters/thanks.snbt"
hash = "4837fdb6f83e86ca518af1febe32b33b11748a18c387e7d10d57620d9d0011d3"

[[files]]
file = "config/ftbquests/quests/chapters/welcome.snbt"
hash = "bc46250afb2d07eece268a470c07094e2282be0a784fe739e78613d811e71ae7"

[[files]]
file = "config/ftbquests/quests/data.snbt"
hash = "e1c35b6eb83293aa6ff91a45e482679a945d16669d405a5feb41606a741cef1d"

[[files]]
file = "config/ftbquests/quests/reward_tables/1_gold_coin.snbt"
hash = "d37793a5f8a65514d4b81dd78f9b1731ae2aa71523b12a4003fc10535f53331f"

[[files]]
file = "config/ftbquests/quests/reward_tables/64_silver_coin.snbt"
hash = "4549a5bf6d2e30fc997325b0321e82bc2db6797cbfa4212c7c4978531755cc81"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "2b006b4a7a087547e840168976cda7fe11d567c571f8e6f9e996506586765426"

[[files]]
file = "config/modmenu.json"
hash = "4e46fecfc73d155cb3f46337f338cd68810687b8dff3d5614c75722a29b0b30a"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "6991409f47b44a87f45441f1c43955c65c09997b1b728751dfa65a0f9ad8e7cc"

[[files]]
file = "config/sodium-extra-options.json"
hash = "682a2cbed83501eb45b11fe9b4b8b56a26c10a777842f8649822547245162ca6"

[[files]]
file = "config/splasher.toml"
hash = "504cc5cf23da31f870e3f763fe256698e9a86db9d8853aedaf3802081b1341f5"

[[files]]
file = "config/splasher/en_us.txt"
hash = "e03f5b4e97de403ae8561fcb67d4f828042d1c2221b1c5539e294fff38698506"

[[files]]
file = "config/splasher/zh_cn.txt"
hash = "90c573249a87a5b4f2c8dc34b661e7a2066c2e8c0804eaf03c8912151e125b81"

[[files]]
file = "config/tconstruct-client.toml"
hash = "78b9a13c7cae6b3106053dbf3d6561457d7ca4dd439fdd3cf865eb604858ec23"

[[files]]
file = "config/waila/waila.json"
hash = "b31359a6ce1057ded98eeeb05e2a10f17a8af2b3023626bd08bae76d9cb72184"

[[files]]
file = "config/waila/waila_plugins.json"
hash = "4ffaeae69f28f4dda6f817311170e4295e737d4178852587aad97b89c8146420"

[[files]]
file = "icon.png"
hash = "2e53e004da6b3e6d4858a6169c1ff6f1d90f54f35af3e6d784bcb718cdad6c4a"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "e5747dab7cf08bee2a062de60685217771615b8276f607e1ad6c6595e9b13197"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "2369de3d3641a7980452bd69816c35e00db7eeab79b6e723b23cd94d879baa1d"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "68c17672bedcc8b65352d63b1bbff131581be1f007c15e621adda9fedcb09fd8"
metafile = true

[[files]]
file = "mods/architects-palette-fabric.pw.toml"
hash = "5d068ee053bfe3b7815d9b28b12144aaf65f9253247eff40480aacf3c2a8e02e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5c067cf953857a327140fca91560dcb225c2f49d8dc5c0e71525812570e8e902"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "c3d163564b8c89694cdcc76060ccd67ea9178a08e18e5d57243a704809f4defc"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
hash = "1dea45a775887e68b1cafb587498dfa5514b3ea8d17ea58783920397f89ff7d7"
metafile = true

[[files]]
file = "mods/bounced.pw.toml"
hash = "2cf8ebde5f3d992ca4a5222419e08647d568db9bf7e2eecf7f4bab44e568491f"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
hash = "7df4d9dc987ad76a0d62a599c609dffb94d7b5103cabfce837c65e56dad969fe"
metafile = true

[[files]]
file = "mods/cabricality-mod.pw.toml"
hash = "c178dae39004acaabc346e82f49bc1214ed0cee8ab371c4b822857435ad9877a"
metafile = true

[[files]]
file = "mods/catwalks-inc.pw.toml"
hash = "435e8b58159a75643f301ec8fd5b9bf984bc0dfa7a60a1e401413a04d5e7ff4c"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "1fb3cbb8ef71a59fbbc722afff7f4f9a9bbaa45838caf0a99f1ed4fce96a4c6c"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "66aa4f271d3c852806c5158f199c507ae4895fcbe5f075278b16bae7b160714b"
metafile = true

[[files]]
file = "mods/cftags-0.1.2.jar"
hash = "e51b7e48c7710b8aa78ca4862e26a238c53a95928587f8f93aa31f2ed4ff48fe"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "77bd9b9ae2bf78481ba939cc78e5e4c0d9528516aa791305eecb39eb56e13125"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b508bb6b509b96b2e297e94ca2ce365623730b938f32c74d49c574a7ef1ecb24"
metafile = true

[[files]]
file = "mods/coxinha-utilities.pw.toml"
hash = "289cf2fb15222b03ed588377b920dcb8dbd8d242b3ea8b76c7e3950925b88d56"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "d17801cdbcb90392e921548c26a123b6ce389d48cb910ae43d828b38ff4fb183"
metafile = true

[[files]]
file = "mods/ctm-refabricated.pw.toml"
hash = "daeb1bc740f2e5dbedff29790e3339418b172cce29b674dbf8eb87fbd6f6d60c"
metafile = true

[[files]]
file = "mods/custom-splash-screen.pw.toml"
hash = "23e3c4cb4e2ee0ed4cd1d9a8e1960578cf3e49839813c7930c4809aba304a1f7"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "b60fc5c154d6ca0e07406638d53bfbaa751e3ef517ff553fcec8543847844728"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1e3d4b62d2b1224356261ca5f9aece724ed2cc6c8f31c77d64867e6bc173ee9d"
metafile = true

[[files]]
file = "mods/equator.pw.toml"
hash = "0a67d114167bfdc3bb31d46b9fe43886ff9ac1279f3c0082dc5d85624bd9ca6a"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "06a9e9d6bc4c512962af46073dcc1b39a21428211159b48c6cac8a99eae6f859"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c985bc9064cc29094fdfd59a037baa1523778cc2a9e5665c3f1b6ca0efe6a543"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "c2d32ced6373731bf691287a6d2daa8c333f38a003d0032264e3174d4aca5eb7"
metafile = true

[[files]]
file = "mods/hephaestus.pw.toml"
hash = "6050b847bd07bbcd6ed9c5801149cde8a4f2393ba308fc7b86dc3c5ccabfa414"
metafile = true

[[files]]
file = "mods/here-be-no-dragons.pw.toml"
hash = "d7d04009eba5c1068bd9aa5214c7ef87dcf426c4f23229b3dbfa6996952fd7c5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "f5751b1f49dfd5d0a78a4573b334651748e02e65dfe093774ab0d0c0886d950c"
metafile = true

[[files]]
file = "mods/industrial-revolution.pw.toml"
hash = "222c0b11598704236ed438f60009b5477bdbdc6d258cbe43731aeaf9c5c1d825"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "7baba0d5b6448760f7a0ad285c82633842efeeda7714571daa477486a4899c50"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "5446a135421d4f9cc9c1f43fa7fdad58bd0eed4c2291a6f51eb03f1ec8fdc6bd"
metafile = true

[[files]]
file = "mods/kibe.pw.toml"
hash = "3e47e98487168bea70eca4a17fd42530ce9fe4b4e1c62d882674e51d181c369a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "219d4425679c60fd2855a6a39a6fccb6db3948dcc57b9da7c20907c855c5bd3d"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/leaves-us-in-peace.pw.toml"
hash = "21da451438c4b95811be685f967b800f0672ac0096bf9a4fc80e08db52902005"
metafile = true

[[files]]
file = "mods/led.pw.toml"
hash = "df9b4bc65e9295704e893adcd1c2bb89d32564b5f13c94743422aa1d62f43fb5"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "7c2779362482a58ce23b6b9c4b377c0aacf80a25bb860c466c4df951052a1b4b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9480f9e11e91eb82ba616c5c622c218d7b7ceff6599a3348d557eb1a1ddd41f9"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
hash = "7154b0157b492f51427845a28530ad4c5181b98f5ceae42d800a83e27167f4ce"
metafile = true

[[files]]
file = "mods/malum-quilt.pw.toml"
hash = "58168b0555e2ff4977a482707eb58fe2c38fd10322ba7a27b00b2866e19a481e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "ec64297b6b7f82ede5ecc46a82e8a0e8dc8b730ee2ad763427b7043389b7a072"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "030b818f7aa75596fe5c0a04b15c66dc0531c79aee5820a30379cc5af77ee46d"
metafile = true

[[files]]
file = "mods/no-unused-chunks.pw.toml"
hash = "73f8c3c2aafcf7c4c504050acdce3f2ca4c9314c6ebbb97258cafabd34c8dce0"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "d240a40073a8ae5c5f56b4c3cde5d78951ca71dc5b8279f0405f346a537659b7"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "90c566f04f86546c14ac20a35e45c593a623b862d26e70ad64f3568b3029acb1"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "4ef251bf925c957e46fa3b223933425df85611d4ddf0e7a04949b38783800a65"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "57a8bedb0057a988cc3a02ed62ef5dcc3331d65df1e7cbebac3789e92858bea0"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "d3cbfc74109c4ff70f7d61d559c7fee5d675762b9265174aaca5625b1629ec9c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "ee3aa9ab24522ccb8cbfcc4ceacab517416594c9ee93e68f82a00b56792e1c3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/splasher.pw.toml"
hash = "9cc11b493efba66e3c481fb317c62a6b96e01a7b82a5d77fe75d0328551c444c"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "722031c0ae5d2de71783d6c4bfbf1c5cd25c65e55cb42d8bb4f7cadf478c4368"
metafile = true

[[files]]
file = "mods/stenographer.pw.toml"
hash = "5c411f588dd6f97f0fbbfe59b8153290b45398e9ad9986e631e7dd96f011c6ee"
metafile = true

[[files]]
file = "mods/structures-compass.pw.toml"
hash = "d616bf7ef5886127a1baa048ac6567267be2c37ef6d2285645ce94871c079793"
metafile = true

[[files]]
file = "mods/terrestria.pw.toml"
hash = "d7390d339169bff9b123b2bc86ca08de1ef10b2991a7923c657bb5bda755c164"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "49f5590e6160266691eaca6948b33a3a2763e590ed4bcf90189f13650066c84e"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "c23e19e793df2ee017103c37c239fb4d7d888641e2f0a02c933f377d9c905390"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.pw.toml"
hash = "bb48e2f46c2ab8c1f4b81cb086ffdf39b4cb5cf6267748d7fc094f42d4bd31c5"
metafile = true
