hash-format = "sha256"

[[files]]
file = ".editorconfig"
hash = "82782271d3e3a34d29ddaa4dcbad17c5f516fafddbc58202c47333f8658a5602"

[[files]]
file = "build.gradle.kts"
hash = "384620cfa7e4ee47ca894845b14c1ee28664f061017d02da5f72ad177058d907"

[[files]]
file = "config/architects_palette.json5"
hash = "a1f8935578d7e7593204c4b42c46af32b435f3cecc2182ac8c5fd7f6c9b503bf"

[[files]]
file = "config/create-common.toml"
hash = "c0e90fd1c6d4a0498cdbd259936812e35b1461eb0d11b4967e2ba32032a5bd44"

[[files]]
file = "config/customsplashscreen.json5"
hash = "0c4ebb39d1bcd398d6c2c7b42c9f2ac641741294e0efe96c6f30a86a7934b8fa"

[[files]]
file = "config/entityculling.json"
hash = "a7395d0ba0d91fad7d584e159dc5428a22554cbb9f4f2c5c5262edfe74362418"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"
hash = "684a97145572aba3c5dc320716c6cb66ff36180ae8f149b9d60249414c83d309"

[[files]]
file = "config/ftbquests/quests/chapters/advancements.snbt"
hash = "073f2d2c9d9cabaf9955f1a7e0b976159ef048847d4d63bb62242558aa2cc65f"

[[files]]
file = "config/ftbquests/quests/chapters/market.snbt"
hash = "6d93a2942179cbbd9da43523f38208d446f0c1ad7215994b0c72cfd5748c7f88"

[[files]]
file = "config/ftbquests/quests/chapters/metallurgy.snbt"
hash = "d4f09e567763cead0b366ea5952e34a799e0be55f6b513fc86fc73659e44817c"

[[files]]
file = "config/ftbquests/quests/chapters/overview.snbt"
hash = "1573137f6fc2afef9fca929fbbfc6179f03794cae9eb5a6d49c929ff46384429"

[[files]]
file = "config/ftbquests/quests/chapters/professions.snbt"
hash = "cb36119bdcf903adbdd825ca947f4f1437d80173bbf88a9a52a0cad56bff1a46"

[[files]]
file = "config/ftbquests/quests/chapters/shipments.snbt"
hash = "644a220cf56a782d850b714a390a25f44fc065874ae50a7fb7c8f9a0d8dcc3d7"

[[files]]
file = "config/ftbquests/quests/chapters/stage_1.snbt"
hash = "9d1e5ee45758c86847a0963618ccd1cfd5e25fae4bc0b2cef6ea1193fcaedf29"

[[files]]
file = "config/ftbquests/quests/chapters/stage_2.snbt"
hash = "8d310817be4dde6f0b17d63adb2ee0caffc35b292796084cc68197a87ef7672a"

[[files]]
file = "config/ftbquests/quests/chapters/stage_3.snbt"
hash = "bb10b49a7ffeac102adeaa29e4ff08dde473554d305a686053344eece028d912"

[[files]]
file = "config/ftbquests/quests/chapters/stage_4.snbt"
hash = "e633f08a5ab08591cbf56a2270e2a3dbc5abeeeab631d08cf045d4ba03623181"

[[files]]
file = "config/ftbquests/quests/chapters/stage_4a.snbt"
hash = "aedf5348e90c7181402394e8f649598b33685b85cd9f1b235cb4f99819b1c9e0"

[[files]]
file = "config/ftbquests/quests/chapters/stage_5.snbt"
hash = "03e5ec081d12831f589148a6fcc26de9957ca464ea0c63b6e94e92ad3c2e6733"

[[files]]
file = "config/ftbquests/quests/chapters/thanks.snbt"
hash = "4837fdb6f83e86ca518af1febe32b33b11748a18c387e7d10d57620d9d0011d3"

[[files]]
file = "config/ftbquests/quests/chapters/welcome.snbt"
hash = "bc46250afb2d07eece268a470c07094e2282be0a784fe739e78613d811e71ae7"

[[files]]
file = "config/ftbquests/quests/data.snbt"
hash = "e1c35b6eb83293aa6ff91a45e482679a945d16669d405a5feb41606a741cef1d"

[[files]]
file = "config/indrev/cables.json"
hash = "9183a2eadef32624ee9a8ed193ac1b61d3b2ce0511f6e0c182f3a2d9bb170a83"

[[files]]
file = "config/indrev/generators.json"
hash = "7e76e3fd7ff40190b24aa76efdea7afc315a87e426ac8d7ce0e0f42a1f4e52c6"

[[files]]
file = "config/indrev/hud.json"
hash = "273c14e99b9b938007693c86b53cd7d697080b38705b1962cfe38104656bcf2d"

[[files]]
file = "config/indrev/machines.json"
hash = "6fbf00f4491111f1be29b4a6dbe172aa90df35cadd5d5ce2cf350bd10e11cbe7"

[[files]]
file = "config/indrev/mining_rig_config.json"
hash = "c9a0a12c14e6d0b9c88d9ed8aa5586ee41435408d814dbf081ae207484b1dc5b"

[[files]]
file = "config/indrev/oregen.json"
hash = "4d7e068bbcd4c51bc53e51395384fc91f05a59092e86a851583e45327c7a0206"

[[files]]
file = "config/indrev/upgrades.json"
hash = "ebbb00fcd5f6a560a60c43c86b71a49a035f154799b6135c1627f14d5f5f72b5"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "2b006b4a7a087547e840168976cda7fe11d567c571f8e6f9e996506586765426"

[[files]]
file = "config/modmenu.json"
hash = "4e46fecfc73d155cb3f46337f338cd68810687b8dff3d5614c75722a29b0b30a"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "ede540a5d9c30280a7668c36afc153f76bc325706e6e961b7ba9ef8dac6f38cf"

[[files]]
file = "config/sodium-extra-options.json"
hash = "682a2cbed83501eb45b11fe9b4b8b56a26c10a777842f8649822547245162ca6"

[[files]]
file = "config/splasher.toml"
hash = "504cc5cf23da31f870e3f763fe256698e9a86db9d8853aedaf3802081b1341f5"

[[files]]
file = "config/splasher/en_us.txt"
hash = "99d25f4f78baff58bbe49099793ee1132c92ef551ebc815a1cb24869d5021ee9"

[[files]]
file = "config/splasher/zh_cn.txt"
hash = "d868560ae52763e97b3ec7a6eb9b784f325f9f549e4e1b35ad91d7d024676542"

[[files]]
file = "config/tconstruct-client.toml"
hash = "78b9a13c7cae6b3106053dbf3d6561457d7ca4dd439fdd3cf865eb604858ec23"

[[files]]
file = "config/waila/waila.json"
hash = "b31359a6ce1057ded98eeeb05e2a10f17a8af2b3023626bd08bae76d9cb72184"

[[files]]
file = "config/waila/waila_plugins.json"
hash = "4ffaeae69f28f4dda6f817311170e4295e737d4178852587aad97b89c8146420"

[[files]]
file = "icon.png"
hash = "2e53e004da6b3e6d4858a6169c1ff6f1d90f54f35af3e6d784bcb718cdad6c4a"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "e298ef09aaef09fa9c5a1e329ec1c143d35d6ba6fe5ab1bf0e3ab9f2c13071b7"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "e362dcd3d782835ef0473ba34e12f17a53d1d296e5f258596420964662fbf7c9"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "16ce27183f78f23c8606787ab2bbbaf01d290b569a4c6d5a6f91b30802ebabd9"
metafile = true

[[files]]
file = "mods/architects-palette-fabric.pw.toml"
hash = "5d068ee053bfe3b7815d9b28b12144aaf65f9253247eff40480aacf3c2a8e02e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a243675bc757485925b293932ee289b9fbcfb3b75bd3ba74eca7603f191cedad"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "368c405be7efc817b528461902c950fbb1f6a9d58cbf561760bae4d5705f96c4"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
hash = "696dedc5f75137914468457f007ecd6d7621a174a22528af2afc6f73b5b867c0"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "d3789633c883daf8aa4c2e5c2f42c0dcb0540eb806ebeee8a44833c25e2de813"
metafile = true

[[files]]
file = "mods/bounced.pw.toml"
hash = "0d41b33c13b1b8df02a37b37290474c6aa1a8329d674e96b8674c13dd03aef2c"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
hash = "b133b5ca4007f772467d0b6fcc1baedcb287bc46d7a2864a83b0e038a51954dd"
metafile = true

[[files]]
file = "mods/bugjump.pw.toml"
hash = "a43ba8d91fcfae5eb51294bb1a5901b80c5d900c6ea7e48aa8f1414801e236ca"
metafile = true

[[files]]
file = "mods/cabricality-mod.pw.toml"
hash = "b716fa3e573f83a01500ab05a530e8f9146ffe72b3af2f0980ba73bd51e469d4"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "c5273660430701af5eb1cb8cc298db8266756bb8bb5c87a6031ce96b33cd8ffc"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6348f94ec939f563285dc96683e61da8fc17ab2f2897be2751fa24789513691"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2ff8353009122a86ac846dd8d48b2522d46f3b43111eb3a697d99cc42285a14f"
metafile = true

[[files]]
file = "mods/coxinha-utilities.pw.toml"
hash = "7665453af22db34c5d1b1438b5aa8d8f03473e3ea90391c3f9cad8b989d83255"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "e5bbc96d6d5d6bffb8e36c89bbd1331d923e23fbb87be8bae208d206832adb1c"
metafile = true

[[files]]
file = "mods/createfabricreibugfix.pw.toml"
hash = "5c4463d9b082ee1e4c9faa67734814296c0f4795735da2e298d7a0f8ddaf059b"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "e6cd8a58a2938b799035c66df16b440db0edf09c798978b8e857a6a27e8a6474"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "31713296359c70914a4fc56d32a61f41620af105819f826bbffbb234591d34fe"
metafile = true

[[files]]
file = "mods/equator.pw.toml"
hash = "9c4162290d73f98d6cc7adca81e77b8df8ea2519840c70a3bb270aa8a397e27b"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "cdb7cd286ed6706a6481a3a07c5017635d322c175351720503f6d59ee38d4020"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f95b9e670d557f852a798489d7b5ec48ed8ddc7e8e1809ff06d4b187d17aac9"
metafile = true

[[files]]
file = "mods/faded-widgets.pw.toml"
hash = "59405a044512301b0007a2cc666a5f0644e4dde5178e1f89b0ceec1681e157e7"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "746344028104ece23ab00e1f73374ed271b492f654bd52ac0ea7c97aad5b362a"
metafile = true

[[files]]
file = "mods/flash.pw.toml"
hash = "b3f42e774beacdba52614578e7f1ae3895b1ef26d39d23afe3b4c188969380ad"
metafile = true

[[files]]
file = "mods/hephaestus.pw.toml"
hash = "dd6d0c4565358f9aa55c9003c2b687c1e759dadb65be16d89a5293f62b51bfe8"
metafile = true

[[files]]
file = "mods/here-be-no-dragons.pw.toml"
hash = "d7d04009eba5c1068bd9aa5214c7ef87dcf426c4f23229b3dbfa6996952fd7c5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "678d1c7827d30fbe8c225e7f2b8ddc29f1dd69cced29335ee5a670477a0728a2"
metafile = true

[[files]]
file = "mods/industrial-revolution.pw.toml"
hash = "5a4ee8f354b74926638df717937223a71f7bbc57786215eec7f4f2efc1b8761a"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "280af6886fbdec37ccfab4d8a7cbd2d3777a198a5fa0d2ec15dc9b9c8b0eff67"
metafile = true

[[files]]
file = "mods/ive-spoken.pw.toml"
hash = "136954b7ff17b866b47c99920e78252895bf639ba7acc7309a089fed072bd02f"
metafile = true

[[files]]
file = "mods/kibe.pw.toml"
hash = "13b13d7612b7aa88f00e24b6b3e412a99b1851f967dcef3401c3debb68539eac"
metafile = true

[[files]]
file = "mods/knowledges.pw.toml"
hash = "021094e4e56a1368d372c736f1fc9fc08900bfdd8d4350daa37b0ed1f3b1faa8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
hash = "53786f23c772395f44842146accd33b2f05bc8113c53dde5ae8c02a98706e83f"
metafile = true

[[files]]
file = "mods/malum-quilt.pw.toml"
hash = "58168b0555e2ff4977a482707eb58fe2c38fd10322ba7a27b00b2866e19a481e"
metafile = true

[[files]]
file = "mods/map-atlases.pw.toml"
hash = "6bdcc4657a59339b1849d1a4757aa551394fe6effc3b602b46f4ddc6933bea85"
metafile = true

[[files]]
file = "mods/modern-dynamics.pw.toml"
hash = "6ed4f74b5a5189086b3d8797162fa27513e72070389e5fe6c80df24ff757f507"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "cb38b82b931ae3c33bf9c21ad0934fcebaebcfe065838ade56a0661e283ee7d6"
metafile = true

[[files]]
file = "mods/no-unused-chunks.pw.toml"
hash = "ad937f7053faacc0d9e84ee3df60e537a380c7d528ca545d6412fd478ae5aa78"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "23583083d03c8effa3dca4c17c7da2fcf57d653292b02898afe8d7029be6b0d7"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "822cb71ea6d0986f90f01d1df5eee941334073cddc7b9abbe0398ba76c31fdaf"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "7d29724ac05ef8982475b92f0e77adf4a4830c249f0e8c1515a19777fbf05f09"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "44b0a2294e1693230308e53b529d671a0303e94b623ba2c2650cdf5760a5a335"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "2c8dba30f0dd63974cba6e2a30bd6a60f1d69bddce537e5cc2137278926d39e0"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4e691c86059e755a026b8cae8cf0c66396dc39bf47b6c71980589101803ecd36"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "bff35d4d3b4fa8c82b5890555d8d9123c223787c545ba7c000c0208b68a72a6d"
metafile = true

[[files]]
file = "mods/splasher.pw.toml"
hash = "63ab6e39458639a11e1bfc461c3f15d8604ba488466a3f3c09d22580367280fc"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/stenographer.pw.toml"
hash = "8c2f2e847343caf8d1fef1744bf343224be42765d78f44c3f738a7f5b534c27b"
metafile = true

[[files]]
file = "mods/structures-compass.pw.toml"
hash = "d616bf7ef5886127a1baa048ac6567267be2c37ef6d2285645ce94871c079793"
metafile = true

[[files]]
file = "mods/terrestria.pw.toml"
hash = "1c43a497cc911474b50a0706b05f1e6040179f1443a59112f2c56157f12c7165"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "b2e02d1210f025b905299bfc88f895058640158343322641aca2c4875622c992"
metafile = true

[[files]]
file = "mods/verticality.pw.toml"
hash = "01a8a2552c9d5bc4998bac640fbbad4b38792da4ff4ee24d43226bfc949d8cc9"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.pw.toml"
hash = "bb48e2f46c2ab8c1f4b81cb086ffdf39b4cb5cf6267748d7fc094f42d4bd31c5"
metafile = true

[[files]]
file = "settings.gradle.kts"
hash = "d0cb0e2215e679f1320f9e6c33bb2b456b0794d9e4d6b712e229b6d8d2cff73a"
